theme: minima
title: My Pages Blog
author: GitHub User
email: Matthewgeary1@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This is the blog of a man looking for work on github while he expands his programing abilitys!
  Maybe if I include somthing about funny cats here I might get a couple of visitors?
  

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Moog84

show_excerpts: true # set to false to remove excerpts on the homepage
